/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import javafx.scene.control.ButtonBar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konfigurasi.koneksi;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;



/**
 *
 * @author Pahan
 */
public class form_mhs extends javax.swing.JFrame {

    private String SQL;
    private String jenis_kelamin;
    private DefaultTableModel TblModel_Mahasiswa;
    

    /**
     * Creates new form form_mhs
     */
    public void TampilData_Mhs() {
        TblModel_Mahasiswa = new DefaultTableModel();
        TblModel_Mahasiswa.addColumn("NIS");
        TblModel_Mahasiswa.addColumn("NAMA MAHASISWA");
        TblModel_Mahasiswa.addColumn("JENIS KELAMIN");
        TblModel_Mahasiswa.addColumn("TANGGAL LAHIR");
        TblModel_Mahasiswa.addColumn("ALAMAT");
        TblModel_Mahasiswa.addColumn("IPK");
        TblModel_Mahasiswa.addColumn("JURUSAN");
        TblModel_Mahasiswa.addColumn("SEMESTER");

        // utk set lebar nama kolom
        table_mahasiswa.setModel(TblModel_Mahasiswa);
        table_mahasiswa.getColumnModel().getColumn(0).setPreferredWidth(50);    // NIS
        table_mahasiswa.getColumnModel().getColumn(1).setPreferredWidth(140);   // NAMA MAHASISWA
        table_mahasiswa.getColumnModel().getColumn(2).setPreferredWidth(100);   // JENIS KELAMIN
        table_mahasiswa.getColumnModel().getColumn(3).setPreferredWidth(120);   // TANGGAL LAHIR
        table_mahasiswa.getColumnModel().getColumn(4).setPreferredWidth(60);    // ALAMAT
        table_mahasiswa.getColumnModel().getColumn(5).setPreferredWidth(40);    // ALAMAT
        table_mahasiswa.getColumnModel().getColumn(6).setPreferredWidth(120);   // JURUSAN
        table_mahasiswa.getColumnModel().getColumn(7).setPreferredWidth(100);   // SEMESTER

        try {
            Connection conn = koneksi.getConnection();
            java.sql.Statement stmt = conn.createStatement();
            SQL = " SELECT * FROM tb_mahasiswa "
                    + " INNER JOIN tb_jurusan ON tb_mahasiswa.id_jurusan = tb_jurusan.id_jurusan "
                    + " INNER JOIN tb_semester ON tb_mahasiswa.id_semester = tb_semester.id_semester ";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                TblModel_Mahasiswa.addRow(new Object[]{
                    res.getString("nis"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("tgl_lahir"),
                    res.getString("alamat"),
                    res.getString("ipk"),
                    res.getString("nama_jurusan"),
                    res.getString("nama_semester"),});
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    private void cmb_jurusan() {
        try {
            Connection conn = koneksi.getConnection();
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM tb_jurusan";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                cbb_jurusan.addItem(res.getString("nama_jurusan"));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void cmb_semester() {
        try {
            Connection conn = koneksi.getConnection();
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM tb_semester";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                cbb_semester.addItem(res.getString("nama_semester"));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public form_mhs() {
        initComponents();
        TampilData_Mhs();
        cmb_jurusan();
        cmb_semester();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio_jenis_kelamin = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_mahasiswa = new javax.swing.JTable();
        Rbtn_lk = new javax.swing.JRadioButton();
        Rbtn_pr = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        txtField_nis = new javax.swing.JTextField();
        txtField_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtField_tgl_lahir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_alamat = new javax.swing.JTextArea();
        cbb_jurusan = new javax.swing.JComboBox<>();
        cbb_semester = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_grafik = new javax.swing.JButton();
        txtField_ipk = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_grafik1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Daftar Mahasiswa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(358, 358, 358))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btn_refresh.setBackground(new java.awt.Color(255, 102, 0));
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_simpan.setBackground(new java.awt.Color(255, 102, 0));
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 102, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        table_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nis", "Nama Mahasiswa", "Jenis Kelamin", "Tanggal Lahir", "Alamat", "Jurusan", "Semester"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_mahasiswa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table_mahasiswa.setSelectionBackground(new java.awt.Color(255, 102, 0));
        table_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mahasiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_mahasiswa);

        radio_jenis_kelamin.add(Rbtn_lk);
        Rbtn_lk.setText("Laki - Laki");
        Rbtn_lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_lkActionPerformed(evt);
            }
        });

        radio_jenis_kelamin.add(Rbtn_pr);
        Rbtn_pr.setText("Perempuan");
        Rbtn_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_prActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 102, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Kembali");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setText(":");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setText("Nama Mahasiswa");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setText("NIS");

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setText(":");

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel9.setText("Tanggal Lahir");

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel10.setText(":");

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel11.setText("Alamat");

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel12.setText(":");

        txtArea_alamat.setColumns(20);
        txtArea_alamat.setRows(3);
        jScrollPane1.setViewportView(txtArea_alamat);

        cbb_jurusan.setBackground(new java.awt.Color(255, 153, 0));
        cbb_jurusan.setForeground(new java.awt.Color(255, 255, 255));
        cbb_jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Jurusan -" }));
        cbb_jurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbb_jurusanMouseClicked(evt);
            }
        });
        cbb_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_jurusanActionPerformed(evt);
            }
        });

        cbb_semester.setBackground(new java.awt.Color(255, 153, 0));
        cbb_semester.setForeground(new java.awt.Color(255, 255, 255));
        cbb_semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Semester -" }));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel13.setText("Jurusan");

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel14.setText("Semester");

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel15.setText(":");

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel16.setText(":");

        btn_grafik.setBackground(new java.awt.Color(255, 102, 0));
        btn_grafik.setForeground(new java.awt.Color(255, 255, 255));
        btn_grafik.setText("Grafik");
        btn_grafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grafikActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel17.setText("IPK");

        jLabel18.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel18.setText(":");

        btn_grafik1.setBackground(new java.awt.Color(255, 102, 0));
        btn_grafik1.setForeground(new java.awt.Color(255, 255, 255));
        btn_grafik1.setText("Video");
        btn_grafik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grafik1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Rbtn_lk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Rbtn_pr))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbb_semester, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbb_jurusan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtField_ipk, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtField_nis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtField_tgl_lahir, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtField_nama, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_refresh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_simpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_grafik)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_grafik1))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtField_nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(Rbtn_lk)
                    .addComponent(Rbtn_pr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(btn_refresh)
                    .addComponent(btn_simpan)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(btn_grafik)
                    .addComponent(btn_grafik1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtField_ipk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(cbb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(cbb_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new form_menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Rbtn_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_prActionPerformed
        // TODO add your handling code here:
        jenis_kelamin = Rbtn_pr.getText();
    }//GEN-LAST:event_Rbtn_prActionPerformed

    private void Rbtn_lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_lkActionPerformed
        // TODO add your handling code here:
        jenis_kelamin = Rbtn_lk.getText();
    }//GEN-LAST:event_Rbtn_lkActionPerformed

    private void table_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mahasiswaMouseClicked
        // TODO add your handling code here:
        try {
            int baris = table_mahasiswa.getSelectedRow();
            txtField_nis.setText(TblModel_Mahasiswa.getValueAt(baris, 0).toString());
            txtField_nama.setText(TblModel_Mahasiswa.getValueAt(baris, 1).toString());
            String jenis = TblModel_Mahasiswa.getValueAt(baris, 2).toString();
            if (jenis.equals("Laki - Laki")) {
                Rbtn_lk.setSelected(true);
            } else if (jenis.equals("Perempuan")) {
                Rbtn_pr.setSelected(true);
            }
            txtField_tgl_lahir.setText(TblModel_Mahasiswa.getValueAt(baris, 3).toString());
            txtArea_alamat.setText(TblModel_Mahasiswa.getValueAt(baris, 4).toString());
            txtField_ipk.setText(TblModel_Mahasiswa.getValueAt(baris, 5).toString());
            cbb_jurusan.setSelectedItem(TblModel_Mahasiswa.getValueAt(baris, 6).toString());
            cbb_semester.setSelectedItem(TblModel_Mahasiswa.getValueAt(baris, 7).toString());
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_table_mahasiswaMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        TampilData_Mhs();
        txtField_nis.setText("");
        txtField_nama.setText("");
        radio_jenis_kelamin.clearSelection();
        txtField_tgl_lahir.setText("");
        txtArea_alamat.setText("");
        txtArea_alamat.setText("");
        txtField_ipk.setText("");
        cbb_jurusan.setSelectedIndex(0);
        cbb_semester.setSelectedIndex(0);


    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:

//        if (txtField_nis.getText().equals("") && txtField_nama.getText().equals("") && radio_jenis_kelamin.getSelection().equals("") && txtField_tgl_lahir.getText().equals("") && txtArea_alamat.getText().equals("") && cbb_jurusan.getSelectedIndex().equals("") && cbb_semester.getSelectedIndex().equals("") ) {
//            JOptionPane.showMessageDialog(null, "Silahkan lengkapi data!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
//        } else {
        try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement(" INSERT INTO tb_mahasiswa(nis, nama, jenis_kelamin, tgl_lahir, alamat, ipk, id_jurusan, id_semester) VALUES (?,?,?,?,?,?,?,?)");
            stmt.setString(1, txtField_nis.getText());
            stmt.setString(2, txtField_nama.getText());
            stmt.setString(3, jenis_kelamin);
            if (Rbtn_lk.isSelected()) {
                jenis_kelamin = "Laki - Laki";
            } else if (Rbtn_pr.isSelected()) {
                jenis_kelamin = "Perempuan";
            }
            stmt.setString(4, txtField_tgl_lahir.getText());
            stmt.setString(5, txtArea_alamat.getText());
            stmt.setString(6, txtField_ipk.getText());
            stmt.setInt(7, cbb_jurusan.getSelectedIndex());
            stmt.setInt(8, cbb_semester.getSelectedIndex());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData_Mhs();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void cbb_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_jurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_jurusanActionPerformed

    private void cbb_jurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbb_jurusanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_jurusanMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Yakin Ingin Menghapus Data Ini??", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0){
            try {
                Connection conn = koneksi.getConnection();
                java.sql.PreparedStatement stmt = conn.prepareStatement("DELETE FROM tb_mahasiswa WHERE nis = '" + txtField_nis.getText() + "'");
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus", "pesan", JOptionPane.INFORMATION_MESSAGE);
                TampilData_Mhs();
                txtField_nis.setText("");
                txtField_nama.setText("");
                radio_jenis_kelamin.clearSelection();
                txtField_tgl_lahir.setText("");
                txtArea_alamat.setText("");
                txtField_ipk.setText("");
                cbb_jurusan.setSelectedIndex(0);
                cbb_semester.setSelectedIndex(0);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + e.getMessage(), "pesan", JOptionPane.ERROR_MESSAGE);
            }
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_grafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grafikActionPerformed
        // TODO add your handling code here:
        try {
            DefaultCategoryDataset data = new DefaultCategoryDataset();
            Connection conn = koneksi.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet set = stmt.executeQuery("SELECT * FROM tb_jurusan");
            while (set.next()) {
                data.setValue(set.getInt("jumlah_mhs"), set.getString("nama_jurusan"), set.getString("nama_jurusan"));
            }
            JFreeChart chart = ChartFactory.createBarChart("Grafik", "Jurusan", "Jumlah", data);
            ChartFrame frame = new ChartFrame("Grafik", chart);
            frame.setVisible(true);
            frame.setBounds(100, 200, 800, 500);
        } catch (SQLException e) {
            System.out.println(e.toString());
        }

    }//GEN-LAST:event_btn_grafikActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("UPDATE tb_mahasiswa SET nama=?, jenis_kelamin=?, tgl_lahir=?, alamat=?, ipk=?, id_jurusan=?, id_semester=? WHERE nis=?");
            stmt.setString(8, txtField_nis.getText());
            stmt.setString(1, txtField_nama.getText());
            stmt.setString(2, jenis_kelamin);
            if (Rbtn_lk.isSelected()) {
                jenis_kelamin = "Laki - Laki";
            } else if (Rbtn_pr.isSelected()) {
                jenis_kelamin = "Perempuan";
            }
            stmt.setString(3, txtField_tgl_lahir.getText());
            stmt.setString(4, txtArea_alamat.getText());
            stmt.setString(5, txtField_ipk.getText());
            stmt.setInt(6, cbb_jurusan.getSelectedIndex());
            stmt.setInt(7, cbb_semester.getSelectedIndex());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData_Mhs();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_grafik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grafik1ActionPerformed
        // TODO add your handling code here:
        new form_video().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_grafik1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_mhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Rbtn_lk;
    private javax.swing.JRadioButton Rbtn_pr;
    private javax.swing.JButton btn_grafik;
    private javax.swing.JButton btn_grafik1;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cbb_jurusan;
    private javax.swing.JComboBox<String> cbb_semester;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup radio_jenis_kelamin;
    private javax.swing.JTable table_mahasiswa;
    private javax.swing.JTextArea txtArea_alamat;
    private javax.swing.JTextField txtField_ipk;
    private javax.swing.JTextField txtField_nama;
    private javax.swing.JTextField txtField_nis;
    private javax.swing.JTextField txtField_tgl_lahir;
    // End of variables declaration//GEN-END:variables
}
