/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konfigurasi.koneksi;

/**
 *
 * @author Pahan
 */
public class form_jurusan_semester extends javax.swing.JFrame {

    /**
     * Creates new form form_jurusan
     */
    private DefaultTableModel TblModel_Jurusan;
    private DefaultTableModel TblModel_Semester;
    private String SQL;
    
    public void TampilData_Jurusan() {
        TblModel_Jurusan = new DefaultTableModel();
        TblModel_Jurusan.addColumn("ID");
        TblModel_Jurusan.addColumn("JURUSAN");
        
        table_jurusan.setModel(TblModel_Jurusan);
        
        try {
            Connection conn = koneksi.getConnection();
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM tb_jurusan";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
            TblModel_Jurusan.addRow(new Object[]{
                res.getString("id_jurusan"),
                res.getString("nama_jurusan"),
                });
                
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    public void TampilData_Semester() {
        TblModel_Semester = new DefaultTableModel();
        TblModel_Semester.addColumn("ID");
        TblModel_Semester.addColumn("SEMESTER");
        
        table_semester.setModel(TblModel_Semester);
        try {
            Connection conn = koneksi.getConnection();
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM tb_semester";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {                
                TblModel_Semester.addRow(new Object[]{
                  res.getString("id_semester"),
                  res.getString("nama_semester"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public form_jurusan_semester() {
        initComponents();
       TampilData_Jurusan();
       TampilData_Semester();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        txtField_jurusan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_jurusan = new javax.swing.JTable();
        tambah_jurusan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtField_semester = new javax.swing.JTextField();
        tambah_semester = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_semester = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        hapus_jurusan = new javax.swing.JButton();
        hapus_semester = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setText("Jurusan");

        table_jurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "JURUSAN"
            }
        ));
        table_jurusan.setSelectionBackground(new java.awt.Color(255, 102, 0));
        table_jurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_jurusanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_jurusan);

        tambah_jurusan.setBackground(new java.awt.Color(255, 102, 0));
        tambah_jurusan.setForeground(new java.awt.Color(255, 255, 255));
        tambah_jurusan.setText("Tambah");
        tambah_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_jurusanActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Semester");

        tambah_semester.setBackground(new java.awt.Color(255, 102, 0));
        tambah_semester.setForeground(new java.awt.Color(255, 255, 255));
        tambah_semester.setText("Tambah");
        tambah_semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_semesterActionPerformed(evt);
            }
        });

        table_semester.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "SEMESTER"
            }
        ));
        table_semester.setSelectionBackground(new java.awt.Color(255, 102, 0));
        table_semester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_semesterMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_semester);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setText("Tambah Jurusan dan Semester");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(111, 111, 111))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        hapus_jurusan.setBackground(new java.awt.Color(255, 102, 0));
        hapus_jurusan.setForeground(new java.awt.Color(255, 255, 255));
        hapus_jurusan.setText("Hapus");
        hapus_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_jurusanActionPerformed(evt);
            }
        });

        hapus_semester.setBackground(new java.awt.Color(255, 102, 0));
        hapus_semester.setForeground(new java.awt.Color(255, 255, 255));
        hapus_semester.setText("Hapus");
        hapus_semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_semesterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtField_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(tambah_jurusan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapus_jurusan))))
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(tambah_semester)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus_semester)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtField_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah_jurusan)
                    .addComponent(hapus_jurusan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tambah_semester)
                    .addComponent(hapus_semester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new form_menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tambah_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_jurusanActionPerformed
        // TODO add your handling code here:
        if (txtField_jurusan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tidak Ada Jurusan Yang Ditambahkan!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }else{
        try {
                Connection conn = koneksi.getConnection();
                PreparedStatement stmt = conn.prepareStatement(" INSERT INTO tb_jurusan(nama_jurusan) VALUES (?)");
                stmt.setString(1, txtField_jurusan.getText());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil Menambahkan Jurusan Baru", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                TampilData_Jurusan();
                txtField_jurusan.setText("");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
        }
        }
    }//GEN-LAST:event_tambah_jurusanActionPerformed

    private void table_jurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_jurusanMouseClicked
        // TODO add your handling code here:
        try {
            int baris = table_jurusan.getSelectedRow();
            txtField_jurusan.setText(TblModel_Jurusan.getValueAt(baris, 1).toString());
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_table_jurusanMouseClicked

    private void hapus_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_jurusanActionPerformed
        // TODO add your handling code here:
        try{
        Connection conn = koneksi.getConnection();
        java.sql.PreparedStatement stmt = conn.prepareStatement("DELETE FROM tb_jurusan WHERE nama_jurusan = '" + txtField_jurusan.getText() + "'");
        stmt.executeUpdate();
        PreparedStatement stmr = conn.prepareStatement("ALTER TABLE tb_jurusan AUTO_INCREMENT=0");
        stmr.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus", "pesan", JOptionPane.INFORMATION_MESSAGE);
        TampilData_Jurusan();
        txtField_jurusan.setText("");
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + e.getMessage(), "pesan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_hapus_jurusanActionPerformed

    private void tambah_semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_semesterActionPerformed
        // TODO add your handling code here:
        if (txtField_semester.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tidak Ada Semester Yang Ditambahkan!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }else{
        try {
                Connection conn = koneksi.getConnection();
                PreparedStatement stmt = conn.prepareStatement(" INSERT INTO tb_semester(nama_semester) VALUES (?)");
                stmt.setString(1, txtField_semester.getText());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil Menambahkan Semester Baru", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                TampilData_Semester();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
        }
        }
    }//GEN-LAST:event_tambah_semesterActionPerformed

    private void table_semesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_semesterMouseClicked
        // TODO add your handling code here:
        try {
            int baris = table_semester.getSelectedRow();
            txtField_semester.setText(TblModel_Semester.getValueAt(baris, 1).toString());
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_table_semesterMouseClicked

    private void hapus_semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_semesterActionPerformed
        // TODO add your handling code here:
        try{
        Connection conn = koneksi.getConnection();
        java.sql.PreparedStatement stmt = conn.prepareStatement("DELETE FROM tb_semester WHERE nama_semester = '" + txtField_semester.getText() + "'");
        stmt.executeUpdate();
        PreparedStatement stmr = conn.prepareStatement("ALTER TABLE tb_semester AUTO_INCREMENT=0");
        stmr.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus", "pesan", JOptionPane.INFORMATION_MESSAGE);
        TampilData_Jurusan();
        txtField_semester.setText("");
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + e.getMessage(), "pesan", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_hapus_semesterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_jurusan_semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_jurusan_semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_jurusan_semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_jurusan_semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_jurusan_semester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus_jurusan;
    private javax.swing.JButton hapus_semester;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_jurusan;
    private javax.swing.JTable table_semester;
    private javax.swing.JButton tambah_jurusan;
    private javax.swing.JButton tambah_semester;
    private javax.swing.JTextField txtField_jurusan;
    private javax.swing.JTextField txtField_semester;
    // End of variables declaration//GEN-END:variables
}
